### PR TITLE
Fix DateTime.fromJSDate input handling

### PR DESCRIPTION
**Pull request by dstelljes**
Restrict input to Dates; produce invalid DateTimes from invalid Dates.

### CODE REVIEW

**Comment by dstelljes** [comment]
Thoughts on the lint? `isNaN` triggers no-restricted-globals, `Number.isNaN` isn't safe, `typeof o === 'number' && o !== o` triggers no-self-compare.

**Comment by icambron** [comment]
Hmm, I've been using `Number.isNaN`. Why isn't it safe? My understanding was that it was *more* safe than the `isNaN` global and hence its restrictions. But I'm just getting that from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN).

**Comment by icambron** [comment]
The patch looks good, btw

**Comment by dstelljes** [comment]
Safe from a browser compatibility standpoint, should have been more clear. I was thinking it was a newer thing, but it looks like it's just IE that doesn't support it.

**Comment by icambron** [comment]
Ah, I see. I polyfilled it here: https://github.com/icambron/luxon/blob/master/src/luxon.js#L4

**Comment by icambron** [comment]
And thanks for the contribution!

**Comment by dstelljes** [comment]
D'oh, didn't even check. And thanks for the library, it's a really neat project!

**Pull request merged**
